# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  schedule: # Run workflow automatically
    - cron: '0 21 * * *' # Runs every hour, on the hour
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: npm install
      - run: node index.js
        env: 
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
          CLOUDFLARE_API: ${{ secrets.CLOUDFLARE_API }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_ID: ${{ secrets.CLOUDFLARE_ID }}
          COVID_ACT_KEY: ${{ secrets.COVID_ACT_KEY }}
          KV_ID: ${{ secrets.KV_ID }}
          UID_ERR: ${{ secrets.UID_ERR }}
